# Generated by Django 4.2 on 2023-04-13 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0004_liker_blog_liketimes_blog_liker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='liker',
        ),
        migrations.AddField(
            model_name='blog',
            name='liker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='liker', to=settings.AUTH_USER_MODEL),
        ),
    ]
