# Generated by Django 4.2 on 2023-04-13 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_times_liker_liketimes_remove_blog_liketimes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='liker',
        ),
        migrations.AddField(
            model_name='blog',
            name='liker',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.liker'),
        ),
    ]
